import pathlib
from typing import Literal

import pytest
import seali


def test_fish_completion_simple_positional(capfd):
    @seali.command
    def foo(x: int, /):
        return x

    with pytest.raises(SystemExit):
        foo(["--completions", "fish"])
    completion = capfd.readouterr().out
    assert "# fish shell completions for foo" in completion
    # Simple types like int don't have specific completions
    assert "auto-generated by seali" in completion


def test_fish_completion_literal_positional(capfd):
    @seali.command
    def foo(choice: Literal["a", "b", "c"], /):
        return choice

    with pytest.raises(SystemExit):
        foo(["--completions", "fish"])
    completion = capfd.readouterr().out
    assert "complete -c foo -n '__fish_is_nth_token 1' -f -a 'a b c'" in completion
    assert "__fish_is_nth_token" in completion


def test_fish_completion_dir_positional(capfd):
    @seali.command
    def foo(file: seali.Dir[str, "."], /):
        return file

    with pytest.raises(SystemExit):
        foo(["--completions", "fish"])
    completion = capfd.readouterr().out
    assert "(ls . 2>/dev/null)" in completion
    assert "__fish_is_nth_token 1" in completion


def test_fish_completion_nocomplete_positional(capfd):
    @seali.command
    def foo(value: seali.NoComplete[str], /):
        return value

    with pytest.raises(SystemExit):
        foo(["--completions", "fish"])
    completion = capfd.readouterr().out
    # NoComplete should not generate completions for positional args
    assert "__fish_is_nth_token" not in completion


def test_fish_completion_flags(capfd):
    @seali.command
    def foo(*, verbose: bool = False, debug: bool = False):
        return (verbose, debug)

    with pytest.raises(SystemExit):
        foo(["--completions", "fish"])
    completion = capfd.readouterr().out
    assert "complete -c foo -s v -l verbose -f" in completion
    assert "complete -c foo -s d -l debug -f" in completion


def test_fish_completion_option_simple(capfd):
    @seali.command
    def foo(*, value: int):
        return value

    with pytest.raises(SystemExit):
        foo(["--completions", "fish"])
    completion = capfd.readouterr().out
    assert "complete -c foo -s v -l value -f -r" in completion


def test_fish_completion_option_literal(capfd):
    @seali.command
    def foo(*, choice: Literal["alpha", "beta", "gamma"]):
        return choice

    with pytest.raises(SystemExit):
        foo(["--completions", "fish"])
    completion = capfd.readouterr().out
    assert "complete -c foo -s c -l choice -f -r -a 'alpha beta gamma'" in completion


def test_fish_completion_option_dir(capfd):
    @seali.command
    def foo(*, file: seali.Dir[str, "/tmp"]):
        return file

    with pytest.raises(SystemExit):
        foo(["--completions", "fish"])
    completion = capfd.readouterr().out
    assert "complete -c foo -s f -l file -f -r -a '(ls /tmp 2>/dev/null)'" in completion


def test_fish_completion_option_nocomplete(capfd):
    @seali.command
    def foo(*, value: seali.NoComplete[str]):
        return value

    with pytest.raises(SystemExit):
        foo(["--completions", "fish"])
    completion = capfd.readouterr().out
    # Should still have the option, but no specific completions
    assert "complete -c foo -s v -l value -f -r" in completion
    # Should not have -a flag with completions
    assert "complete -c foo -s v -l value -r -a" not in completion


def test_fish_completion_union_literal(capfd):
    @seali.command
    def foo(*, choice: Literal["a", "b"] | Literal["c", "d"]):
        return choice

    with pytest.raises(SystemExit):
        foo(["--completions", "fish"])
    completion = capfd.readouterr().out
    # Union should combine all literals
    assert "a b c d" in completion


def test_fish_completion_union_with_nocomplete(capfd):
    @seali.command
    def foo(*, value: Literal["a", "b"] | seali.NoComplete[int]):
        return value

    with pytest.raises(SystemExit):
        foo(["--completions", "fish"])
    completion = capfd.readouterr().out
    # Should have literals but not int completions
    assert "a b" in completion


def test_fish_completion_mixed(capfd):
    @seali.command
    def foo(
        pos: Literal["start", "stop"],
        /,
        *,
        config: seali.Dir[str, "~/.config"],
        mode: Literal["fast", "slow"] = "fast",
        verbose: bool = False,
    ):
        return (pos, config, mode, verbose)

    with pytest.raises(SystemExit):
        foo(["--completions", "fish"])
    completion = capfd.readouterr().out
    # Positional literal
    assert "start stop" in completion
    # Option with Dir
    assert "(ls ~/.config 2>/dev/null)" in completion
    # Option with Literal
    assert "fast slow" in completion
    # Flag
    assert "complete -c foo -s v -l verbose -f" in completion


def test_fish_completion_kebab_case(capfd):
    @seali.command
    def foo(*, my_option: int, another_flag: bool = False):
        return (my_option, another_flag)

    with pytest.raises(SystemExit):
        foo(["--completions", "fish"])
    completion = capfd.readouterr().out
    # Should convert underscores to hyphens
    assert "-l my-option" in completion
    assert "-l another-flag" in completion


def test_fish_completion_custom_cmd_name(capfd):
    @seali.command
    def my_custom_name(x: int, /):
        return x

    with pytest.raises(SystemExit):
        my_custom_name(["--completions", "fish"])
    completion = capfd.readouterr().out
    assert "# fish shell completions for my_custom_name" in completion
    # Simple types like int don't have specific completions
    assert "auto-generated by seali" in completion


def test_fish_completion_default_cmd_name(capfd):
    @seali.command
    def my_program(x: int, /):
        return x

    with pytest.raises(SystemExit):
        my_program(["--completions", "fish"])
    completion = capfd.readouterr().out
    assert "# fish shell completions for my_program" in completion
    # Simple types like int don't have specific completions
    assert "auto-generated by seali" in completion


def test_fish_completion_multiple_positional_with_literal(capfd):
    @seali.command
    def foo(first: Literal["a", "b"], second: Literal["x", "y", "z"], /):
        return (first, second)

    with pytest.raises(SystemExit):
        foo(["--completions", "fish"])
    completion = capfd.readouterr().out
    assert "__fish_is_nth_token 1" in completion
    assert "__fish_is_nth_token 2" in completion
    assert "a b" in completion
    assert "x y z" in completion


def test_fish_completion_dir_with_path(capfd):
    @seali.command
    def foo(*, file: seali.Dir[pathlib.Path, "/var/log"]):
        return file

    with pytest.raises(SystemExit):
        foo(["--completions", "fish"])
    completion = capfd.readouterr().out
    assert "(ls /var/log 2>/dev/null)" in completion


def test_fish_completion_union_dir(capfd):
    @seali.command
    def foo(*, value: seali.Dir[str, "."] | seali.Dir[str, "/tmp"]):
        return value

    with pytest.raises(SystemExit):
        foo(["--completions", "fish"])
    completion = capfd.readouterr().out
    # Both directories should be listed
    assert "(ls . 2>/dev/null)" in completion
    assert "(ls /tmp 2>/dev/null)" in completion


def test_fish_completion_no_args(capfd):
    @seali.command
    def foo():
        return None

    with pytest.raises(SystemExit):
        foo(["--completions", "fish"])
    completion = capfd.readouterr().out
    assert "# fish shell completions for foo" in completion
    # Should not have any argument completions
    assert "complete -c foo -s" not in completion
    assert "__fish_is_nth_token" not in completion


def test_fish_completion_only_simple_types(capfd):
    @seali.command
    def foo(x: int, /, *, name: str, count: float):
        return (x, name, count)

    with pytest.raises(SystemExit):
        foo(["--completions", "fish"])
    completion = capfd.readouterr().out
    # Simple types without special completion annotations
    assert "complete -c foo -s n -l name -f -r" in completion
    assert "complete -c foo -s c -l count -f -r" in completion
    # No specific completions for the types
    assert " -a " not in completion or "complete -c foo -s" in completion


def test_fish_completion_dir_empty_string_option(capfd):
    @seali.command
    def foo(*, file: seali.Dir[str, ""]):
        return file

    with pytest.raises(SystemExit):
        foo(["--completions", "fish"])
    completion = capfd.readouterr().out
    # Empty string directory should offer default file completion
    # This means -r without -a, allowing fish's built-in file completion
    assert "complete -c foo -s f -l file -r" in completion
    # Should not have ls command
    assert "(ls" not in completion
    # Should not have -a flag with a specific completion
    assert "complete -c foo -s f -l file -r -a" not in completion


def test_fish_completion_dir_empty_string_positional(capfd):
    @seali.command
    def foo(file: seali.Dir[str, ""], /):
        return file

    with pytest.raises(SystemExit):
        foo(["--completions", "fish"])
    completion = capfd.readouterr().out
    # Empty string directory for positional should not add specific completions
    # This allows fish's default file completion to work
    assert "__fish_is_nth_token" not in completion
    assert "(ls" not in completion


def test_fish_completion_dir_str_option(capfd):
    @seali.command
    def foo(*, file: seali.Dir[str]):  # pyright: ignore[reportInvalidTypeForm]
        return file

    with pytest.raises(SystemExit):
        foo(["--completions", "fish"])
    completion = capfd.readouterr().out
    # Dir[str] without directory should offer default file completion
    # This means -r without -a, allowing fish's built-in file completion
    assert "complete -c foo -s f -l file -r" in completion
    # Should not have ls command
    assert "(ls" not in completion
    # Should not have -a flag with a specific completion
    assert "complete -c foo -s f -l file -r -a" not in completion


def test_fish_completion_dir_str_positional(capfd):
    @seali.command
    def foo(file: seali.Dir[str], /):  # pyright: ignore[reportInvalidTypeForm]
        return file

    with pytest.raises(SystemExit):
        foo(["--completions", "fish"])
    completion = capfd.readouterr().out
    # Dir[str] without directory for positional should not add specific completions
    # This allows fish's default file completion to work
    assert "__fish_is_nth_token" not in completion
    assert "(ls" not in completion


def test_fish_completion_dir_path_option(capfd):
    @seali.command
    def foo(*, file: seali.Dir[pathlib.Path]):  # pyright: ignore[reportInvalidTypeForm]
        return file

    with pytest.raises(SystemExit):
        foo(["--completions", "fish"])
    completion = capfd.readouterr().out
    # Dir[pathlib.Path] without directory should offer default file completion
    # This means -r without -a, allowing fish's built-in file completion
    assert "complete -c foo -s f -l file -r" in completion
    # Should not have ls command
    assert "(ls" not in completion
    # Should not have -a flag with a specific completion
    assert "complete -c foo -s f -l file -r -a" not in completion


def test_fish_completion_dir_path_positional(capfd):
    @seali.command
    def foo(file: seali.Dir[pathlib.Path], /):  # pyright: ignore[reportInvalidTypeForm]
        return file

    with pytest.raises(SystemExit):
        foo(["--completions", "fish"])
    completion = capfd.readouterr().out
    # Dir[pathlib.Path] without directory for positional should not add specific
    # completions
    # This allows fish's default file completion to work
    assert "__fish_is_nth_token" not in completion
    assert "(ls" not in completion


def test_fish_completion_multiple_args_same_first_letter(capfd):
    @seali.command
    def foo(*, verbose: bool = False, value: int = 0, vector: str = ""):
        return (verbose, value, vector)

    with pytest.raises(SystemExit):
        foo(["--completions", "fish"])
    completion = capfd.readouterr().out
    # Only the first argument (verbose) should have -s v
    assert "complete -c foo -s v -l verbose -f" in completion
    # The other arguments should not have -s v
    assert "complete -c foo -s v -l value" not in completion
    assert "complete -c foo -s v -l vector" not in completion
    # But they should still have their long forms
    assert "complete -c foo -l value -f -r" in completion
    assert "complete -c foo -l vector -f -r" in completion


def _with_name(name):
    def _with_name_impl(fn):
        fn.__name__ = name
        return fn

    return _with_name_impl


def test_fish_completion_subcommand_with_spaces(capfd):
    @seali.command
    @_with_name("foo bar")
    def foo(*, verbose: bool = False, value: int = 0):
        return (verbose, value)

    with pytest.raises(SystemExit):
        foo(["--completions", "fish"])
    completion = capfd.readouterr().out

    # Should use base command "foo" in complete -c
    assert "complete -c foo" in completion
    # Should NOT use "complete -c foo bar"
    assert "complete -c foo bar" not in completion
    # Should have subcommand condition for flags/options
    assert "__fish_seen_subcommand_from bar" in completion
    # Verify the format is correct
    assert (
        "complete -c foo -n '__fish_seen_subcommand_from bar' -s v -l verbose -f"
        in completion
    )
    # value doesn't get -s v because verbose already has it
    assert (
        "complete -c foo -n '__fish_seen_subcommand_from bar' -l value -f -r"
        in completion
    )


def test_fish_completion_nested_subcommand_with_spaces(capfd):
    @seali.command
    @_with_name("git remote add")
    def foo(choice: Literal["a", "b"], /, *, debug: bool = False):
        return (choice, debug)

    with pytest.raises(SystemExit):
        foo(["--completions", "fish"])
    completion = capfd.readouterr().out

    # Should use base command "git" in complete -c
    assert "complete -c git" in completion
    # Should have subcommand condition with both subcommands
    assert "__fish_seen_subcommand_from remote add" in completion
    # Flag should have the condition
    assert (
        "complete -c git -n '__fish_seen_subcommand_from remote add' -s d -l debug -f"
        in completion
    )
    # Positional should have combined conditions
    assert (
        "__fish_seen_subcommand_from remote add; and __fish_is_nth_token 3"
        in completion
    )


def test_fish_completion_with_help(capfd):
    @seali.command(
        help=seali.Help("Test help", seali.Style(), dict(verbose="bar"), {})
    )
    def foo(*, verbose: bool = False):
        return verbose

    with pytest.raises(SystemExit):
        foo(["--completions", "fish"])
    completion = capfd.readouterr().out
    # Should have help flag
    assert "complete -c foo -s h -l help -f" in completion
    # Should also have the regular flag
    assert "complete -c foo -s v -l verbose -f" in completion


def test_fish_completion_with_version(capfd):
    @seali.command(version="1.0.0")
    def foo(*, debug: bool = False):
        return debug

    with pytest.raises(SystemExit):
        foo(["--completions", "fish"])
    completion = capfd.readouterr().out
    # Should have version flag
    assert "complete -c foo -s v -l version -f" in completion
    # Should also have the regular flag
    assert "complete -c foo -s d -l debug -f" in completion


def test_fish_completion_with_help_and_version(capfd):
    @seali.command(
        help=seali.Help("Test help", seali.Style(), dict(quiet="qasdf"), {}),
        version="2.0.0",
    )
    def foo(*, quiet: bool = False):
        return quiet

    with pytest.raises(SystemExit):
        foo(["--completions", "fish"])
    completion = capfd.readouterr().out
    # Should have both help and version flags
    assert "complete -c foo -s h -l help -f" in completion
    assert "complete -c foo -s v -l version -f" in completion
    # Should also have the regular flag
    assert "complete -c foo -s q -l quiet -f" in completion


def test_fish_completion_without_help_or_version(capfd):
    @seali.command
    def foo(*, verbose: bool = False):
        return verbose

    with pytest.raises(SystemExit):
        foo(["--completions", "fish"])
    completion = capfd.readouterr().out
    # Should NOT have help or version flags
    assert "-l help" not in completion
    assert "-l version" not in completion
    # Should have the regular flag
    assert "complete -c foo -s v -l verbose -f" in completion


def test_fish_completion_help_with_subcommand(capfd):
    @seali.command(
        help=seali.Help(
            "Test help", seali.Style(), dict(force="whether to force"), {}
        )
    )
    @_with_name("myapp deploy")
    def foo(*, force: bool = False):
        return force

    with pytest.raises(SystemExit):
        foo(["--completions", "fish"])
    completion = capfd.readouterr().out
    # Help flag should have subcommand condition
    assert (
        "complete -c myapp -n '__fish_seen_subcommand_from deploy' -s h -l help -f"
    ) in completion
    # Regular flag should also have subcommand condition
    assert (
        "complete -c myapp -n '__fish_seen_subcommand_from deploy' -s f -l force -f"
        in completion
    )


def test_fish_completion_version_with_subcommand(capfd):
    @seali.command(version="3.0.0")
    @_with_name("cli tool")
    def foo(*, debug: bool = False):
        return debug

    with pytest.raises(SystemExit):
        foo(["--completions", "fish"])
    completion = capfd.readouterr().out
    # Version flag should have subcommand condition
    assert (
        "complete -c cli -n '__fish_seen_subcommand_from tool' -s v -l version -f"
    ) in completion
    # Regular flag should also have subcommand condition
    assert (
        "complete -c cli -n '__fish_seen_subcommand_from tool' -s d -l debug -f"
        in completion
    )


def test_fish_completion_version_no_conflict_with_verbose(capfd):
    """Test that version flag takes -s v and verbose doesn't get it"""

    @seali.command(version="1.0.0")
    def foo(*, verbose: bool = False):
        return verbose

    with pytest.raises(SystemExit):
        foo(["--completions", "fish"])
    completion = capfd.readouterr().out
    # Version should get -s v
    assert "complete -c foo -s v -l version -f" in completion
    # Verbose should NOT get -s v (should only have long form)
    assert "complete -c foo -l verbose -f" in completion
    # Verbose should NOT have -s v in its completion line
    lines = completion.split("\n")
    verbose_lines = [l for l in lines if "-l verbose" in l]
    assert len(verbose_lines) == 1
    assert "-s v" not in verbose_lines[0]


def test_fish_completion_help_no_conflict_with_host(capfd):
    """Test that help flag takes -s h and host doesn't get it"""

    @seali.command(
        help=seali.Help(
            "Test", seali.Style(), dict(host="the host"), dict(host="host")
        )
    )
    def foo(*, host: str = "localhost"):
        return host

    with pytest.raises(SystemExit):
        foo(["--completions", "fish"])
    completion = capfd.readouterr().out
    # Help should get -s h
    assert "complete -c foo -s h -l help -f" in completion
    # Host should NOT get -s h (should only have long form)
    assert "complete -c foo -l host -f -r" in completion
    # Host should NOT have -s h in its completion line
    lines = completion.split("\n")
    host_lines = [l for l in lines if "-l host" in l]
    assert len(host_lines) == 1
    assert "-s h" not in host_lines[0]


def test_fish_completion_both_help_version_no_conflicts(capfd):
    """Test that both help and version take their short flags without conflicts"""

    @seali.command(
        help=seali.Help(
            "Test",
            seali.Style(),
            dict(verbose="verbosity", host="the host"),
            dict(host="host"),
        ),
        version="1.0.0",
    )
    def foo(*, verbose: bool = False, host: str = "localhost"):
        return (verbose, host)

    with pytest.raises(SystemExit):
        foo(["--completions", "fish"])
    completion = capfd.readouterr().out

    # Help should get -s h
    assert "complete -c foo -s h -l help -f" in completion
    # Version should get -s v
    assert "complete -c foo -s v -l version -f" in completion

    # Parse lines to check verbose and host
    lines = completion.split("\n")
    verbose_lines = [l for l in lines if "-l verbose" in l]
    host_lines = [l for l in lines if "-l host" in l]

    # Verbose should NOT get -s v
    assert len(verbose_lines) == 1
    assert "-s v" not in verbose_lines[0]

    # Host should NOT get -s h
    assert len(host_lines) == 1
    assert "-s h" not in host_lines[0]
