import dataclasses
import functools as ft
import sys
from collections.abc import Callable
from typing import overload

from ._arguments import Arguments, UsageError
from ._completions import completions
from ._doc_utils import doc_remove_return
from ._help import Help


@dataclasses.dataclass(frozen=True)
class Command:
    fn: Callable
    help: None | Help
    version: None | str
    extra_completions: None | Callable[[str], list[str]]

    # Not computed eagerly to minimise overhead when launching the script.
    @ft.cached_property
    def arguments(self):
        return Arguments.from_callable(
            self.fn, self.help is not None, self.version is not None
        )

    def completions(self, shell: str, parent_command: None | str) -> list[str]:
        out = completions(
            shell,
            self.fn.__name__
            if parent_command is None
            else parent_command + " " + self.fn.__name__,
            self.arguments,
            self.help,
            has_version=self.version is not None,
        )
        if self.extra_completions is not None:
            out.extend(self.extra_completions(shell))
        return out

    def __call__(self, argv: None | list[str] = None):
        try:
            if argv is None:
                argv = sys.argv[1:]
            if self.help is not None:
                if argv == ["-h"] or argv == ["--help"]:
                    # We don't eagerly check all `argv`. This is so that
                    # `maincmd subcmd --help` can trigger the `subcmd`'s help, not the
                    # `maincmd`'s help.
                    # In the event of a usage error, we perform an eager check below.
                    self.help.pager(self.fn.__name__, self.arguments)
                    sys.exit(2)
            if self.version is not None:
                if argv == ["-v"] or argv == ["--version"]:
                    print(self.version)
                    sys.exit(0)
            if len(argv) == 2 and argv[0] == "--completions":
                shell = argv[1]
                completions = self.completions(shell, None)
                print(f"# {shell} shell completions for {self.fn.__name__}")
                print("# This was auto-generated by tinycli")
                for line in completions:
                    print(line)
                sys.exit(2)
            try:
                parsed = self.arguments.parse(list(argv))
            except UsageError:
                if self.help is not None:
                    for arg in argv:
                        if arg in {"-h", "--help"}:
                            self.help.pager(self.fn.__name__, self.arguments)
                            sys.exit(2)
                raise
            return self.fn(*parsed.args, **parsed.kwargs)
        except KeyboardInterrupt:  # Control-C
            sys.exit(130)
        except EOFError:  # Control-D
            sys.exit(0)


@overload
def command(
    fn: None = None,
    *,
    help: None | Help = None,
    version: None | str = None,
    extra_completions: None | Callable[[str], list[str]] = None,
) -> Callable[[Callable], Command]: ...


@overload
def command(
    fn: Callable,
    *,
    help: None | Help = None,
    version: None | str = None,
    extra_completions: None | Callable[[str], list[str]] = None,
) -> Command: ...


@doc_remove_return
def command(
    fn: None | Callable = None,
    *,
    help: None | Help = None,
    version: None | str = None,
    extra_completions: None | Callable[[str], list[str]] = None,
) -> Command | Callable[[Callable], Command]:
    """Wires a function up to the CLI.

    **Arguments:**

    - `fn`: the function to decorate.

        All arguments must be type-annotated. Supported types are `None`, `str`, `bool`,
        `int`, `float`, `pathlib.Path`, `Literal`s and `Union`s. Command line inputs are
        automatically parsed into the specified type.

        All arguments must be either be positional-only (before a `/`), keyword-only
        (after a `*`), or variadic-positional (`*args`).

        Positional-only arguments may or may have default values.

        Keyword-only arguments...

        - ...with `bool`ean annotations are 'flags'. Flags must have default `False`.
        - ...with any other annotation are 'options'. These may or may not have a
            default.

    - `help`: optional, the documentation for the function. Appears when running with
        `-h` or `--help`. Should be a [`tinycli.Help`][] object.

    - `version`: optional, the version to report when running with `-v` or `--version`.

    - `extra_completions`: optional, a function which will be called with the shell (for
        example `"fish"`) and which should return any extra completions for this
        command.

    **Returns:**

    A command object that can be called with nothing, or with a list of strings. If
    called with nothing, defaults to `sys.argv[1:]`.

    **Command line inputs:**

    The inputs are scanned left-to-right. If the input begins with a `-` then it is
    treated as an option or flag. Otherwise it is treated positionally. (To pass
    positional arguments that happen to begin with a `-`, then pass `--`: all arguments
    after this are treated positionally, regardless of what they start with.)

    Options are set either by `--opt=value` or via `--opt value`.

    Flags are set by passing them without a value, `--flag`.

    Flags and options may be called with either `--kebab-case` or `--snake_case`. The
    first argument beginning with each letter may be input with just a single-letter
    abbreviation, e.g. `-f` instead of `--flag`.

    If there are too many positional inputs, or any unknown flags or options, then...
    <br>
    ...if there is a variadic-positional argument, then they will be passed in to this
    unchanged.
    <br>
    ...if there is no variadic-positional argument, then an error will be raised.

    !!! Example

        ```python
        @tinycli.command  # or @tinycli.command(help=...)
        def my_program(pos: str, /, *, someflag: bool = False):
            ...

        if __name__ == "__main__":
            my_program()  # same as `my_program(sys.argv)`
                          # or use `my_program(custom_argv)` to customise parsed args
        ```
    """
    if fn is None:
        return ft.partial(
            command, help=help, version=version, extra_completions=extra_completions
        )
    return Command(fn, help, version, extra_completions)
